meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

  releases:
  - {name: cf, version: latest}
  - {name: java-buildpack, version: latest}
  - {name: go-buildpack, version: latest}
  - {name: binary-buildpack, version: latest}
  - {name: nodejs-buildpack, version: latest}
  - {name: ruby-buildpack, version: latest}
  - {name: php-buildpack, version: latest}
  - {name: python-buildpack, version: latest}
  - {name: staticfile-buildpack, version: latest}
  - {name: dotnet-core-buildpack, version: latest}
  - {name: secureproxy, version: latest}

name: (( meta.environment ))

director_uuid: (( merge ))

releases: (( merge || meta.releases ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 5
  network: cf1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: true

resource_pools: (( merge ))

disk_pools: (( merge ))
